# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_chatterbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=128)),
                ('gender', models.CharField(blank=True, help_text='Categorical variable to facilitate personality learning', max_length=32)),
                ('chat_age', models.FloatField(blank=True, help_text='Scalar between 0 and 100 estimating age of a user based solely on their chat style, word choice.', max_length=32, null=True)),
                ('kindness', models.FloatField(blank=True, default=0.0, help_text='Probability (0-1) of making a kind statement')),
                ('hurtfulness', models.FloatField(default=0.0, help_text='Probability (0-1) of making an unkind, cruel, hurtful statement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('positivity', models.FloatField(default=0.0, help_text='Positive valence (emotion) in a statement (VADER by Hutto, C.J. & Gilbert)')),
                ('negativity', models.FloatField(default=0.0, help_text='Negative valence (emotion) in a statement (VADER by Hutto, C.J. & Gilbert)')),
                ('neutrality', models.FloatField(default=0.0, help_text='Negative valence (emotion) in a statement (VADER by Hutto, C.J. & Gilbert)')),
                ('intensity', models.FloatField(default=0.0, help_text='Emotional intensity (from VADER by Hutto, C.J. & Gilbert)')),
                ('kindness', models.FloatField(default=0.0, help_text='Probability (0-1) of making a kind statement')),
                ('sarcasm', models.FloatField(default=0.0, help_text='Lack of sincerity in a statement')),
                ('readability', models.FloatField(default=0.0, help_text='Probability (0-1) of making a kind statement')),
                ('chat_age', models.FloatField(default=0.0, help_text='Oldfashioned-ness, negative hipness, in mean age of the utterance distribution in time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='response',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='response',
            name='prompt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='django_chatterbot.Statement', verbose_name='Prompting statement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='responses',
            field=models.ManyToManyField(through='django_chatterbot.Response', to='django_chatterbot.Statement'),
        ),
        migrations.AlterField(
            model_name='response',
            name='occurrence',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this statement has been used to respond to the statement in `in_response_to`.'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='django_chatterbot.Statement', verbose_name='Response statement'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='response',
            name='statement',
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('prompt', 'response')]),
        ),
        migrations.AddField(
            model_name='statement',
            name='chat_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_chatterbot.ChatUser'),
        ),
        migrations.AddField(
            model_name='statement',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_chatterbot.Score'),
        ),
    ]
