# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=128)),
                ('gender', models.CharField(blank=True, help_text='Categorical variable to facilitate personality learning', max_length=32)),
                ('chat_age', models.FloatField(blank=True, help_text='Scalar between 0 and 100 estimating age of a user based solely on their chat style, word choice.', max_length=32, null=True)),
                ('kindness', models.FloatField(blank=True, default=0.0, help_text='Probability (0-1) of making a kind statement')),
                ('hurtfulness', models.FloatField(default=0.0, help_text='Probability (0-1) of making an unkind, cruel, hurtful statement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='response',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statement',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_chatterbot.User'),
            preserve_default=False,
        ),
    ]
