# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='responses',
            field=models.ManyToManyField(default=None, through='django_chatterbot.Response', to='django_chatterbot.Statement'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_chatterbot.Statement'),
        ),
    ]
