# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0002_auto_20161001_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='django_chatterbot.Statement'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('statement', 'response')]),
        ),
    ]
