# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0002_auto_20160930_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_chatterbot.User'),
        ),
    ]
