# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0002_auto_20160927_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='django_chatterbot.Statement', verbose_name='Prompting statement'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_chatterbot.Statement', verbose_name='Response statement'),
        ),
    ]
