# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0003_auto_20160928_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='negativity',
        ),
        migrations.RemoveField(
            model_name='score',
            name='neutrality',
        ),
        migrations.RemoveField(
            model_name='score',
            name='positivity',
        ),
        migrations.AddField(
            model_name='score',
            name='compound',
            field=models.FloatField(default=0.0, help_text='VADER compound valence intensity from NLTK.SentimentIntensityAnalyzer (see Hutto, C.J. & Gilbert)'),
        ),
        migrations.AddField(
            model_name='score',
            name='negative',
            field=models.FloatField(default=0.0, help_text='VADER negative valence (emotion) intensity in a statement (see Hutto, C.J. & Gilbert)'),
        ),
        migrations.AddField(
            model_name='score',
            name='neutral',
            field=models.FloatField(default=0.0, help_text='VADER neutral valence (emotion) intensity in a statement (see Hutto, C.J. & Gilbert)'),
        ),
        migrations.AddField(
            model_name='score',
            name='positive',
            field=models.FloatField(default=0.0, help_text='VADER positive valence (emotion) intensity in a statement (see Hutto, C.J. & Gilbert)'),
        ),
    ]
