# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0004_auto_20160930_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatuser',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='chatuser',
            old_name='modified_date',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='modified_date',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='modified_date',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='chat_user',
            new_name='chatuser',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='statement',
            old_name='modified_date',
            new_name='modified',
        ),
    ]
