# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0004_auto_20160928_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='dale_chall',
            field=models.FloatField(default=0.0, help_text='Readability percent, 0-100, based on occurrence of 3000 most common English words (from `textstat.dale_chall_readability_score`)'),
        ),
        migrations.AddField(
            model_name='score',
            name='flesch',
            field=models.FloatField(default=0.0, help_text='Flesch Reading Ease based on sylable, word, and sentence counts (from `readability.superficial_measures["readability grades"]`).'),
        ),
        migrations.AddField(
            model_name='score',
            name='kincaid',
            field=models.FloatField(default=0.0, help_text='Kincaid grade level (from `readbility.superficial_measures["readability grades"]`)'),
        ),
    ]
