# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0005_auto_20160928_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='chat_age',
            field=models.FloatField(blank=True, default=None, help_text='Oldfashioned-ness, negative hipness, in mean age of the utterance distribution in time', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='compound',
            field=models.FloatField(blank=True, default=None, help_text='VADER compound valence intensity from NLTK.SentimentIntensityAnalyzer (see Hutto, C.J. & Gilbert)', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='dale_chall',
            field=models.FloatField(blank=True, default=None, help_text='Readability percent, 0-100, based on occurrence of 3000 most common English words (from `textstat.dale_chall_readability_score`)', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='flesch',
            field=models.FloatField(blank=True, default=None, help_text='Flesch Reading Ease based on sylable, word, and sentence counts (from `readability.superficial_measures["readability grades"]`).', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='intensity',
            field=models.FloatField(blank=True, default=None, help_text='Emotional intensity (from VADER by Hutto, C.J. & Gilbert)', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='kincaid',
            field=models.FloatField(blank=True, default=None, help_text='Kincaid grade level (from `readbility.superficial_measures["readability grades"]`)', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='kindness',
            field=models.FloatField(blank=True, default=None, help_text='Probability (0-1) of making a kind statement', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='negative',
            field=models.FloatField(blank=True, default=None, help_text='VADER negative valence (emotion) intensity in a statement (see Hutto, C.J. & Gilbert)', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='neutral',
            field=models.FloatField(blank=True, default=None, help_text='VADER neutral valence (emotion) intensity in a statement (see Hutto, C.J. & Gilbert)', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='positive',
            field=models.FloatField(blank=True, default=None, help_text='VADER positive valence (emotion) intensity in a statement (see Hutto, C.J. & Gilbert)', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='readability',
            field=models.FloatField(blank=True, default=None, help_text='Probability (0-1) of making a kind statement', null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='sarcasm',
            field=models.FloatField(blank=True, default=None, help_text='Lack of sincerity in a statement', null=True),
        ),
    ]
