# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0006_auto_20160928_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_response_to', to='django_chatterbot.Statement', verbose_name='Prompting statement'),
        ),
    ]
